import * as path from "node:path";

import { readJsonIfExists, readTextIfExists, writeJsonEnsured, writeTextEnsured } from "../workflow-guard-core/fs";
import { resolveProjectArtifactPath } from "../workflow-guard-core/paths";
import {
  DEFAULT_SURVEY_VISUAL_COMPILER_STATE_PATH,
  DEFAULT_SURVEY_VISUAL_EVIDENCE_ROWS_PATH,
  DEFAULT_SURVEY_VISUAL_INSERTION_MAP_PATH,
  serializeSurveyVisualCompilerState,
  type SurveyVisualCompilerState,
  type SurveyVisualEvidenceRow,
} from "../workflow-guard-state/survey-visual-compiler";

function uniqueStrings(values: Array<string | null | undefined>): string[] {
  const seen = new Set<string>();
  const results: string[] = [];
  for (const value of values) {
    const normalized = typeof value === "string" ? value.trim() : "";
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    results.push(normalized);
  }
  return results;
}

function collectMarkdownSignalLines(rawText: string | null | undefined, limit = 8): string[] {
  if (!rawText) {
    return [];
  }
  const lines = rawText
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("#") && !/^[-*_]{3,}$/.test(line))
    .map((line) => line.replace(/^[-*]\s+/, ""))
    .filter((line) => line.length > 0);
  return uniqueStrings(lines).slice(0, limit);
}

function renderTaxonomyTable(rows: SurveyVisualEvidenceRow[]): string {
  const body = rows
    .filter((row) => row.kind === "taxonomy")
    .slice(0, 6)
    .map(
      (row) =>
        `${row.label ?? "Family"} & representative methods here & ${row.evidence ?? "evidence here"} & ${row.caveat ?? "caveat here"} \\\\`
    );
  return `%% Auto-generated by survey visual compiler
\\begin{table*}[t]
\\centering
\\caption{Survey taxonomy overview.}
\\begin{tabular}{p{0.14\\textwidth} p{0.22\\textwidth} p{0.34\\textwidth} p{0.2\\textwidth}}
\\hline
Family / Theme & Representative methods & Evidence summary & Caveat / boundary \\\\
\\hline
${body.length > 0 ? body.join("\n") : "Family A & representative methods here & evidence here & caveat here \\\\"}
\\hline
\\end{tabular}
\\end{table*}
`;
}

function renderBenchmarkTable(rows: SurveyVisualEvidenceRow[]): string {
  const body = rows
    .filter((row) => row.kind === "benchmark" || row.kind === "tradeoff")
    .slice(0, 8)
    .map(
      (row) =>
        `${row.label ?? "Method / benchmark"} & ${row.evidence ?? "evidence here"} & ${row.caveat ?? "caveat here"} \\\\`
    );
  return `%% Auto-generated by survey visual compiler
\\begin{table*}[t]
\\centering
\\caption{Benchmark / comparison landscape.}
\\begin{tabular}{p{0.24\\textwidth} p{0.42\\textwidth} p{0.24\\textwidth}}
\\hline
Method / comparison axis & Evidence summary & Caveat / fairness warning \\\\
\\hline
${body.length > 0 ? body.join("\n") : "Method A & evidence here & caveat here \\\\"}
\\hline
\\end{tabular}
\\end{table*}
`;
}

export async function materializeSurveyVisualCompiler(params: {
  projectRoot: string;
}): Promise<{
  generatedFiles: string[];
  rowCount: number;
}> {
  const manifestPath = path.join(params.projectRoot, "PROJECT_MANIFEST.json");
  const manifest =
    (await readJsonIfExists<Record<string, unknown>>(manifestPath)) ?? {};
  const surveyReview =
    manifest.survey_review && typeof manifest.survey_review === "object"
      ? (manifest.survey_review as Record<string, unknown>)
      : {};
  const topic =
    (typeof surveyReview.topic === "string" && surveyReview.topic.trim()) || "the survey topic";

  const [
    surveyBrief,
    literatureReview,
    sotaMatrix,
    gapSynthesis,
    reviewProtocol,
    assetIndex,
  ] = await Promise.all([
    readTextIfExists(path.join(params.projectRoot, "researcher", "SURVEY_BRIEF.md")),
    readTextIfExists(path.join(params.projectRoot, "researcher", "LITERATURE_REVIEW.md")),
    readTextIfExists(path.join(params.projectRoot, "researcher", "SOTA_MATRIX.md")),
    readTextIfExists(path.join(params.projectRoot, "researcher", "GAP_SYNTHESIS.md")),
    readTextIfExists(path.join(params.projectRoot, "researcher", "REVIEW_PROTOCOL.md")),
    readJsonIfExists<Record<string, unknown>>(
      path.join(params.projectRoot, "academic_writer", "SURVEY_VISUAL_ASSET_INDEX.json")
    ),
  ]);

  const taxonomyLines = uniqueStrings([
    ...collectMarkdownSignalLines(surveyBrief, 6),
    ...collectMarkdownSignalLines(literatureReview, 6),
  ]).slice(0, 6);
  const benchmarkLines = uniqueStrings([
    ...collectMarkdownSignalLines(sotaMatrix, 8),
    ...collectMarkdownSignalLines(reviewProtocol, 5),
  ]).slice(0, 8);
  const tradeoffLines = collectMarkdownSignalLines(gapSynthesis, 5);

  const rows: SurveyVisualEvidenceRow[] = [
    ...taxonomyLines.map((line, index) => ({
      rowId: `taxonomy-${index + 1}`,
      kind: "taxonomy" as const,
      label: `Family ${index + 1}`,
      evidence: line,
      caveat: null,
      sourceArtifacts: ["researcher/SURVEY_BRIEF.md", "researcher/LITERATURE_REVIEW.md"],
    })),
    ...benchmarkLines.map((line, index) => ({
      rowId: `benchmark-${index + 1}`,
      kind: "benchmark" as const,
      label: `Benchmark ${index + 1}`,
      evidence: line,
      caveat: null,
      sourceArtifacts: ["researcher/SOTA_MATRIX.md", "researcher/REVIEW_PROTOCOL.md"],
    })),
    ...tradeoffLines.map((line, index) => ({
      rowId: `tradeoff-${index + 1}`,
      kind: "tradeoff" as const,
      label: `Tradeoff ${index + 1}`,
      evidence: line,
      caveat: "Verify that the manuscript frames this as an open problem or limitation, not settled consensus.",
      sourceArtifacts: ["researcher/GAP_SYNTHESIS.md"],
    })),
  ];

  const evidenceRowsPath = resolveProjectArtifactPath(
    params.projectRoot,
    DEFAULT_SURVEY_VISUAL_EVIDENCE_ROWS_PATH
  );
  const compilerStatePath = resolveProjectArtifactPath(
    params.projectRoot,
    DEFAULT_SURVEY_VISUAL_COMPILER_STATE_PATH
  );
  const insertionMapPath = resolveProjectArtifactPath(
    params.projectRoot,
    DEFAULT_SURVEY_VISUAL_INSERTION_MAP_PATH
  );
  const taxonomyTablePath = path.join(
    params.projectRoot,
    "academic_writer",
    "paper",
    "tables",
    "survey_taxonomy_overview.tex"
  );
  const benchmarkTablePath = path.join(
    params.projectRoot,
    "academic_writer",
    "paper",
    "tables",
    "survey_benchmark_landscape.tex"
  );
  if (!evidenceRowsPath || !compilerStatePath || !insertionMapPath) {
    throw new Error("Unable to resolve survey visual compiler paths.");
  }

  await writeJsonEnsured(evidenceRowsPath, {
    schema_version: 1,
    generated_at: new Date().toISOString(),
    topic,
    rows,
  });
  await writeTextEnsured(taxonomyTablePath, renderTaxonomyTable(rows));
  await writeTextEnsured(benchmarkTablePath, renderBenchmarkTable(rows));
  await writeJsonEnsured(insertionMapPath, {
    generated_at: new Date().toISOString(),
    topic,
    inserts: [
      {
        section: "taxonomy",
        assets: ["academic_writer/paper/tables/survey_taxonomy_overview.tex"],
      },
      {
        section: "benchmark_landscape",
        assets: ["academic_writer/paper/tables/survey_benchmark_landscape.tex"],
      },
      {
        section: "evidence_synthesis",
        assets: ["academic_writer/SURVEY_VISUAL_EVIDENCE_ROWS.json"],
      },
    ],
  });
  const state: SurveyVisualCompilerState = {
    status: rows.length > 0 ? "ready" : "waiting",
    topic,
    evidenceRowsPath: DEFAULT_SURVEY_VISUAL_EVIDENCE_ROWS_PATH,
    insertionMapPath: DEFAULT_SURVEY_VISUAL_INSERTION_MAP_PATH,
    assetIndexPath: "academic_writer/SURVEY_VISUAL_ASSET_INDEX.json",
    taxonomyTablePath: "academic_writer/paper/tables/survey_taxonomy_overview.tex",
    benchmarkTablePath: "academic_writer/paper/tables/survey_benchmark_landscape.tex",
    taxonomyFigureSpecPath: "academic_writer/paper/figures/survey_taxonomy_map.md",
    benchmarkFigureSpecPath: "academic_writer/paper/figures/survey_benchmark_comparison_map.md",
    rowCount: rows.length,
    generatedAssetCount:
      2 + ((Array.isArray(assetIndex?.figureSpecs) ? assetIndex.figureSpecs.length : 0) ?? 0),
    pendingReason:
      rows.length === 0
        ? "Survey evidence rows are still empty; expand SURVEY_BRIEF.md / SOTA_MATRIX.md / REVIEW_PROTOCOL.md before treating visuals as ready."
        : null,
    lastUpdatedAt: new Date().toISOString(),
  };
  await writeJsonEnsured(compilerStatePath, {
    schema_version: 1,
    ...serializeSurveyVisualCompilerState(state),
  });
  manifest.survey_visual_compiler_state = serializeSurveyVisualCompilerState(state);
  await writeJsonEnsured(manifestPath, manifest);

  return {
    generatedFiles: [
      DEFAULT_SURVEY_VISUAL_EVIDENCE_ROWS_PATH,
      DEFAULT_SURVEY_VISUAL_COMPILER_STATE_PATH,
      DEFAULT_SURVEY_VISUAL_INSERTION_MAP_PATH,
      "academic_writer/paper/tables/survey_taxonomy_overview.tex",
      "academic_writer/paper/tables/survey_benchmark_landscape.tex",
    ],
    rowCount: rows.length,
  };
}
